version: "3.5"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${version_confluent}
    hostname: zk-1
    networks:
      - workshop
    volumes:
      - ./agents:/agents
      - data-zookeeper:/var/lib/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
  kafka:
    image: confluentinc/cp-kafka:${version_confluent}
    hostname: kafka-1
    networks:
      - workshop
    ports:
      - 9092:9092
      - 1098:1098
    volumes:
      - ./agents:/agents
      - data-kafka:/var/lib/kafka/data
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 6
      KAFKA_JMX_OPTS: "${JMX_ARGS}"
      # source: https://stackoverflow.com/questions/77467885/i-configured-javaagent-for-kafka-jmx-exporter-and-now-i-cant-create-topic-or-ge
      EXTRA_ARGS: "-javaagent:/agents/jmx_prometheus_javaagent-0.10.jar=7071:/agents/kafka.yaml"
      JMX_PROMETHEUS_PORT: 7071



  kafka-connect:
    image: confluentinc/cp-kafka-connect:${version_confluent}
    hostname: kafka-connect
    networks:
      - workshop
    ports:
      - 8083:8083
      - 1099:1099  # JMX port
      - 7071:7071  # Prometheus JMX exporter port
    volumes:
      - ./agents:/agents
      - data-kafka-connect:/var/lib/kafka/data
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      # JMX Configuration
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka-connect -Dcom.sun.management.jmxremote.rmi.port=1099"
      KAFKA_JMX_PORT: 1099
      # source: https://stackoverflow.com/questions/77467885/i-configured-javaagent-for-kafka-jmx-exporter-and-now-i-cant-create-topic-or-ge
      EXTRA_ARGS: "-javaagent:/agents/jmx_prometheus_javaagent-0.10.jar=7071:/agents/kafka-connect.yaml"
      JMX_PROMETHEUS_PORT: 707k

volumes:
  data-zookeeper:
  data-kafka:
  data-kafka-connect:

networks:
  workshop: